# Generated by Django 4.2.4 on 2023-09-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Titutlo del Comentario'),
        ),
    ]
